job:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  kind: CronJob
  schedule: "*/10 * * * *"
  global:
    jobKind: CronJob
  keyVaults:
    am:
      secrets:
        - AppInsightsInstrumentationKey
        - am-role-assignment-refresh-batch-s2s-secret
        - orm-IDAM-CLIENT-ID
        - orm-IDAM-CLIENT-SECRET
        - orm-IDAM-ADMIN-SECRET
  environment:
    #ORG_ROLE_MAPPING_DB_HOST: "{{ .Release.Name }}-postgresql"
    ORG_ROLE_MAPPING_DB_HOST: am-org-role-mapping-service-pr-145-postgresql-0
    ORG_ROLE_MAPPING_DB_NAME: "{{ .Values.postgresql.postgresqlDatabase}}"
    ORG_ROLE_MAPPING_DB_USERNAME: "{{ .Values.postgresql.postgresqlUsername}}"
    ORG_ROLE_MAPPING_DB_PASSWORD: "{{ .Values.postgresql.postgresqlPassword}}"
    ORG_ROLE_MAPPING_DB_PORT: "{{ .Values.postgresql.postgresqlPort}}"
    ORG_ROLE_MAPPING_DB_OPTIONS: "?stringtype=unspecified"
postgresql:
  enabled: false
  postgresqlUsername: org_role_mapping
  postgresqlPassword: org_role_mapping
  postgresqlDatabase: org_role_mapping
  postgresqlPort: 5432