server:
  port: ${PORT:5333}

spring:
  application:
    name: Role Assignment Refresh Batch
  config:
    import: "optional:configtree:/mnt/secrets/am/"
  batch:
    initialize-schema: always
    job:
      enabled: true
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  jackson:
    default-property-inclusion: NON_NULL
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    log_statement: all
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${ORG_ROLE_MAPPING_DB_HOST:localhost}:${ORG_ROLE_MAPPING_DB_PORT:5451}/${ORG_ROLE_MAPPING_DB_NAME:org_role_mapping}${ORG_ROLE_MAPPING_DB_OPTIONS:?stringtype=unspecified}
    username: ${ORG_ROLE_MAPPING_DB_USERNAME:}
    password: ${ORG_ROLE_MAPPING_DB_PASSWORD:}
    properties:
      charSet: UTF-8

feign:
  hystrix:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 15000
        readTimeout: 15000
        loggerLevel: basic
      ormClient:
        url: ${AM_ORM_URL:http://localhost:4098}
      rasClient:
        url: ${AM_RAS_URL:http://localhost:4096}
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 4000

roleAssignmentRefreshBatchUrl: ${TEST_URL:http://localhost:5333}
refresh-orm-records: refresh-orm-records
batchjob-name: refreshORMRulesBatchJob
batch-size: 20
refresh-job-delay-duration: ${REFRESH_JOB_DELAY_DURATION:60000}

idam:
  s2s-auth:
    totp_secret: ${AM_ROLE_ASSIGNMENT_REFRESH_BATCH_SECRET:}
    microservice: am_role_assignment_refresh_batch
    url: ${IDAM_S2S_URL:http://localhost:4502}
  api.url: ${IDAM_USER_URL:http://localhost:5000}
  client:
    id: ${ORM_IDAM_CLIENT_ID:am_docker}
    secret: ${ORG_ROLE_MAPPING_IDAM_CLIENT_SECRET:}
    redirect_uri: ${ORG_ROLE_MAPPING_IDAM_REDIRECT_URI:http://localhost:4096/oauth2redirect}
    admin:
      userId: ${ORG_ROLE_MAPPING_IDAM_ADMIN_USERID:}
      secret: ${ORG_ROLE_MAPPING_IDAM_ADMIN_PASSWORD:}
      scope: ${ORG_ROLE_MAPPING_IDAM_ADMIN_SCOPE:openid profile roles authorities}

logging.level.uk.gov.hmcts: ${APPLICATION_LOGGING_LEVEL:INFO}

launchdarkly:
  sdk:
    key: ${LD_SDK_KEY:}
    environment: ${LAUNCH_DARKLY_ENV:pr}
    user: am-${LAUNCH_DARKLY_ENV:local}